FROM node:22-alpine as builder

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY ./ ./

RUN npm run build:compose

###

FROM nginx:alpine

WORKDIR /usr/share/nginx/html/

RUN rm -rf *

COPY --from=builder /app/dist ./

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

CMD [ "nginx", "-g", "daemon off;" ]